<?php
session_start();
if(!isset($_SESSION["digiecool"])){
    header("Location:login.php");
    die();
}
require_once("_config/config.php");
require_once("body/header.php");
require_once("body/".PREFIXE."menu.php");
require_once($content);
require_once("body/footer.php");
 ?>
