public class MyFrame extends JFrame {
 
	private JLabel nomLabel;
	private JButton nomButton = new JButton("Fenetre Fille");
 
	public static void main(String[] args) {
		MyFrame myFrame = new MyFrame();
	}
 
	public MyFrame() {
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		getContentPane().setLayout(new BorderLayout());
		nomLabel = new JLabel();
		nomLabel.setPreferredSize(new Dimension(150, 19));
		getContentPane().add(nomButton, BorderLayout.NORTH);
		getContentPane().add(nomLabel, BorderLayout.CENTER);
 
		nomButton.addActionListener(new NomButtonListener(this));
		pack();
		java.awt.Dimension screenSize =
			java.awt.Toolkit.getDefaultToolkit().getScreenSize();
 
		this.setLocation(
			(screenSize.width - this.getWidth()) / 2,
			(screenSize.height - this.getHeight()) / 2);
 
		show();
	}
 
	class NomButtonListener implements ActionListener {
		MyDialog nomDialog;
		public NomButtonListener(JFrame parent) {
			nomDialog = new MyDialog(parent);
		}
 
		public void actionPerformed(ActionEvent arg0) {
			nomDialog.show();
			if (nomDialog.getReturnStatus() == MyDialog.RET_OK) {
				nomLabel.setText(nomDialog.getNomEntre());
			}
		}
	} //:-
 
	class MyDialog extends javax.swing.JDialog {
		/** A return status code - returned if Cancel button has been pressed */
		public static final int RET_CANCEL = 0;
		/** A return status code - returned if OK button has been pressed */
		public static final int RET_OK = 1;
 
		private String nomEntre;
 
		public MyDialog(java.awt.Frame parent) {
			super(parent, true);
			initComponents();
			myInit();
		}
 
		public void myInit() {
			java.awt.Dimension screenSize =
				java.awt.Toolkit.getDefaultToolkit().getScreenSize();
 
			this.setLocation(
				(screenSize.width - this.getWidth()) / 2,
				(screenSize.height - this.getHeight()) / 2);
 
		} //myInit
 
		/** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
		public int getReturnStatus() {
			return returnStatus;
		}
 
		/** This method is called from within the constructor to
                        * initialize the form.
                        * WARNING: Do NOT modify this code. The content of this method is
                        * always regenerated by the Form Editor.
                        */
		private void initComponents() {
			buttonPanel = new javax.swing.JPanel();
			okButton = new javax.swing.JButton();
			cancelButton = new javax.swing.JButton();
 
			setTitle("Entrez votre nom");
			addWindowListener(new java.awt.event.WindowAdapter() {
				public void windowClosing(java.awt.event.WindowEvent evt) {
					closeDialog(evt);
				}
			});
 
			buttonPanel.setLayout(
				new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
			buttonPanel.setBackground(new java.awt.Color(51, 102, 255));
			okButton.setText("OK");
			okButton.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {
					okButtonActionPerformed(evt);
				}
			});
 
			buttonPanel.add(okButton);
 
			cancelButton.setText("Cancel");
			cancelButton
				.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {
					cancelButtonActionPerformed(evt);
				}
			});
 
			buttonPanel.add(cancelButton);
 
			getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);
 
			textField.setPreferredSize(new Dimension(150, 19));
			getContentPane().add(textField, java.awt.BorderLayout.CENTER);
 
			pack();
		}
 
		private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {
			nomEntre = textField.getText();
			doClose(RET_OK);
		}
 
		private void cancelButtonActionPerformed(
			java.awt.event.ActionEvent evt) {
			doClose(RET_CANCEL);
		}
 
		/** Closes the dialog */
		private void closeDialog(java.awt.event.WindowEvent evt) {
			doClose(RET_CANCEL);
		}
 
		private void doClose(int retStatus) {
			returnStatus = retStatus;
			setVisible(false);
			dispose();
		}
 
		// Variables declaration - do not modify
		private javax.swing.JPanel buttonPanel;
		private JTextField textField = new JTextField();
		private javax.swing.JButton cancelButton;
		private javax.swing.JButton okButton;
		// End of variables declaration
 
		private int returnStatus = RET_CANCEL;
 
		/**
                        * @return
                        */
		public javax.swing.JButton getOkButton() {
			return okButton;
		}
 
		/**
                        * @param panel
                        */
		public void setButtonPanel(javax.swing.JPanel panel) {
			buttonPanel = panel;
		}
 
		/**
                        * @param button
                        */
		public void setCancelButton(javax.swing.JButton button) {
			cancelButton = button;
		}
 
		/**
                        * @param button
                        */
		public void setOkButton(javax.swing.JButton button) {
			okButton = button;
		}
 
		/**
                        * @param i
                        */
		public void setReturnStatus(int i) {
			returnStatus = i;
		}
 
		/**
                 * @return
                 */
		public String getNomEntre() {
			return nomEntre;
		}
	} //:-
 
} ///:-